image: python:3.10.4-alpine

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

install-poetry:
  stage: build
  script:
    - apk add musl-dev libffi-dev gcc  # Poetry dependencies
    - pip install poetry

install-dependencies:
    stage: build
    script:
    - poetry install

run-tests: 
  stage: test
  script:
    - poetry run pytest
    - echo "All tests passed!"
