image: python:3.10.4-alpine

stages:          # List of stages for jobs, and their order of execution
  - test

run-tests:
  stage: test
  script:
    - apk add musl-dev libffi-dev gcc  # Poetry dependencies
    - pip install poetry
    - poetry install
    - poetry run pytest
    - echo "All tests passed!"